version: '3'

services:
 ldap:
   image: osixia/openldap
   volumes:
     - ./data/slapd/database:/var/lib/ldap
     - ./data/slapd/config:/etc/ldap/slapd.d
  #environment:
  #  - LDAP_ORGANISATION="teamdigitale"
  #   - LDAP_DOMAIN="teamdigitale.it"
  #   - LDAP_ADMIN_PASSWORD="admin"
   ports:
     - "389:389"
     - "636:636"

 phpldapadmin:
   image: osixia/phpldapadmin
   ports:
     - "80:80"
   environment:
     - PHPLDAPADMIN_HTTPS="false"
     - PHPLDAPADMIN_LDAP_HOSTS=ldap
   links:
     - ldap
   depends_on:
     - ldap
