version: '3'

services:
  jupyterhub:
    container_name: jupyterhub
    image: jupyterhub
    restart: always
    extra_hosts:
      idm.daf.gov.it: 192.168.0.29
      livy.default.svc.cluster.local: 192.168.0.27
    links:
        - postgresjupyterhub
    environment:
        POSTGRES_HOST: "postgresjupyterhub"
        POSTGRES_DB: "jupyterhub"
        POSTGRES_USER: "jupyterhub"
        POSTGRES_PASSWORD: "jupyterhub"
    ports:
        - "8000:8000"
    volumes:
        - ./jupyterhubconfig:/srv/jupyterhub
    networks:
        - back

  postgresjupyterhub:
    container_name: postgresjupyterhub
    image: postgres:9.6
    restart: always
    ports:
        - "5432:5432"
    environment:
        POSTGRES_DB: jupyterhub
        POSTGRES_PASSWORD: jupyterhub
        POSTGRES_USER: jupyterhub
    # volumes:
    #     - postgres:/var/lib/postgresql/data
    networks:
        - back


networks:
    back:
        # use the bridge driver, but enable IPv6
        driver: bridge
